name: 'Test packages installation'
description: 'This action test packages installation in Suse Centos Debian'
inputs:
  TAG: 
    description: 'Tag of the integration to test'
    required: true
    default: '0.0.0'
  INTEGRATION: 
    description: 'Integration to test'
    required: true
    default: 'nri-test'
outputs:
  random-number: 
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps: 
    - run: |
        docker build -f dockerfiles-test/Dockerfile-suse .
        docker build -f dockerfiles-test/Dockerfile-cendos .
        docker build -f dockerfiles-test/Dockerfile-debian .
      shell: bash
