name: 'Test packages installation'
description: 'This action test packages installation in Suse Centos Debian'
inputs:
  TAG: 
    description: 'Tag of the integration to test'
    required: true
    default: '0.0.0'
  INTEGRATION: 
    description: 'Integration to test'
    required: true
    default: 'nri-test'
  TEST_EXISTENCE:
    description: 'file to test es "/var /bin/nri-test"'
    required: false
    default: ''
runs:
  using: "composite"
  env:
    TAG: ${{ inputs.TAG }}
    INTEGRATION: ${{ inputs.INTEGRATION }}
    TEST_EXISTENCE: ${{ inputs.TEST_EXISTENCE }}
  steps: 
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
