name: 'Test packages installation'
description: 'This action test packages installation in Suse Centos Debian'
inputs:
  tag:
    description: 'Tag of the integration to test'
    required: true
    default: '0.0.0'
  integration:
    description: 'Name of the integration to test'
    required: true
    default: 'nri-test'
  upgrade:
    description: 'Wether to test upgrade path as well'
    required: false
    default: "true"
  postInstall:
    description: 'Script to run after installation is completed. Default will test for existence of the integration binary and -show_version output'
    required: false
    default: ""
  postInstallExtra:
    description: 'Extra check lines to append to the default postInstall script.'
    required: false
    default: ""
#  skip:
#    description: 'Space separated list of distros to skip testing on. Valid valued are "debian", "suse" and "centos"'
#    required: false
#    default: ""
#  upgradeFrom:
#    description: 'Override which package to test the upgrade path from. Defaults to the latest version of `integration` in the NR repo.'
#    required: false
#    default: ""

runs:
  using: "composite"
  steps: 
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        TAG: ${{ inputs.tag }}
        INTEGRATION: ${{ inputs.integration }}
        UPGRADE: ${{ inputs.upgrade }}
        POST_INSTALL: ${{ inputs.postInstall }}
        POST_INSTALL_EXTRA: ${{ inputs.postInstallExtra }}
#        SKIP: ${{ inputs.skip }}
