name: Self-test linux action

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  linux-local:
    runs-on: ubuntu-latest
    name: Local linux self-test
    strategy:
      matrix:
        distro: [ ubuntu, suse, centos ]
    steps:
      - uses: actions/checkout@v2
      - name: Test local package on ${{ matrix.distro }}
        uses: ./linux
        with:
          tag: '1.3.0'
          integration: 'nri-snmp'
          upgrade: false # Needed for self-test not to fail due to downgrading package
          pkgDir: testdata/dist
          distros: ${{ matrix.distro }}

  linux-remote:
    runs-on: ubuntu-latest
    name: Remote linux self-test
    strategy:
      matrix:
        distro: [ ubuntu, suse, centos ]
    steps:
      - uses: actions/checkout@v2
      - name: Test staging package on ${{ matrix.distro }}
        uses: ./linux
        with:
          tag: '1'
          integration: 'nri-snmp'
          upgrade: false
          packageLocation: 'repo'
          stagingRepo: true
          distros: ${{ matrix.distro }}
