name: Self-test windows action

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  msi-package:
    runs-on: windows-2019
    name: A job to test created packages
    strategy:
      matrix:
        goarch: [amd64,386]
        # We need a clean runner (not using containers here) to execute each installation test type. 
        test-upgrade: [true,false]
    steps:
      - uses: actions/checkout@v2
      - uses: ./windows
        with:
          tag: 'v2.2.0'
          integration: 'nri-haproxy'
          arch: ${{ matrix.goarch }}
          upgrade: ${{ matrix.test-upgrade }}
          pkgDir: 'testdata\windows'

  exe-package:
    runs-on: windows-2019
    name: Test exe packages
    steps:
      - uses: actions/checkout@v2
      - uses: ./windows
        timeout-minutes: 10
        with:
          tag: 'v9.9.9'
          integration: 'nri-cassandra'
          arch: amd64
          upgrade: false
          pkgDir: 'testdata\windows'
          pkgName: "nri-cassandra-amd64-installer.9.9.9.exe"
