name: Self-test windows action

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  msi-package:
    runs-on: windows-2019
    name: Test msi package
    strategy:
      matrix:
        goarch: [amd64,386]
    steps:
      - uses: actions/checkout@v2
      - uses: ./windows
        timeout-minutes: 10
        with:
          tag: 'v2.2.0'
          repoVersion: 'v2.2.0'
          integration: 'nri-haproxy'
          arch: ${{ matrix.goarch }}
          upgrade: false
          pkgDir: 'testdata\windows'

  exe-package:
    runs-on: windows-2019
    name: Test exe package
    steps:
      - uses: actions/checkout@v2
      - uses: ./windows
        timeout-minutes: 10
        with:
          tag: 'v9.9.9'
          repoVersion: 'v9.9.9'
          integration: 'nri-cassandra'
          arch: amd64
          upgrade: false
          pkgType: "exe"
          pkgDir: 'testdata\windows'
