name: Self-test linux action

on:
  push:
    branches:
      - master
      - main
  pull_request:

# ATTENTION
# This is a self-test pipeline and it is *NOT* intended to be used as a base/quickstart on how to
# use the action. Please refer to the examples in the README.md file for that

jobs:
  linux-local:
    runs-on: ubuntu-latest
    name: Local linux self-test
    strategy:
      matrix:
        distro: [ ubuntu, suse, centos ]
    steps:
      - uses: actions/checkout@v2
      - name: Test local package on ${{ matrix.distro }}
        uses: ./linux
        with:
          tag: '1.3.0'
          integration: 'nri-snmp'
          upgrade: false # Needed for self-test not to fail due to downgrading package
          pkgDir: testdata/dist
          distros: ${{ matrix.distro }}

  linux-local-update:
    runs-on: ubuntu-latest
    name: Local linux self-test with upgrade apt
    strategy:
      matrix:
        distro: [ ubuntu ]
    steps:
      - uses: actions/checkout@v2
      - name: Test local package on ${{ matrix.distro }}
        uses: ./linux
        with:
          tag: '9.9.9'
          integration: 'nri-mssql'
          pkgDir: testdata/dist
          distros: ${{ matrix.distro }}

  linux-remote:
    runs-on: ubuntu-latest
    name: Remote linux self-test
    strategy:
      matrix:
        distro: [ ubuntu, suse, centos ]
    steps:
      - uses: actions/checkout@v2
      - name: Test staging package on ${{ matrix.distro }}
        uses: ./linux
        with:
          tag: '.' # Match anything, just for testing
          integration: 'nri-haproxy'
          upgrade: false
          packageLocation: 'repo'
          pkgDir: testdata/dist # PKGDir must exist or docker will fail to `COPY` things
          stagingRepo: true
          distros: ${{ matrix.distro }}
