name: Self-test linux action

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    name: A job to test created packages
    strategy:
      matrix:
        distro: [ ubuntu, suse, centos ]
    steps:
    - uses: actions/checkout@v2
    - name: Test local package on ${{ matrix.distro }}
      uses: ./linux
      with:
        tag: '1.3.0'
        integration: 'nri-snmp'
        upgrade: true
        pkgDir: testdata/dist
        distros: ${{ matrix.distro }}
    - name: Test staging package on ${{ matrix.distro }}
      uses: ./linux
      with:
        tag: '1'
        integration: 'nri-snmp'
        upgrade: false
        packageLocation: 'repo'
        stagingRepo: true
        distros: ${{ matrix.distro }}
