on: [push]

jobs:
  test_packages_job:
    runs-on: ubuntu-latest
    name: A job to test created packages
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        TAG: '0.0.1'
        INTEGRATION: 'nri-apache'
        TEST_EXISTENCE: '/var/db/newrelic-infra/newrelic-integrations/bin/nri-apache /etc/newrelic-infra/integrations.d/nri-apache-config.yml.sample /var/db/newrelic-infra/newrelic-integrations/nri-apache-definition.yml'