on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test created packages
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        TAG: '0.0.1'
        INTEGRATION: 'nri-apache'