on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    name: A job to test created packages
    steps:
    - uses: actions/checkout@v2
    - name: Simulating Build
      run: |
        mkdir ./dist
        wget https://github.com/newrelic/nri-apache/releases/download/v0.0.1/nri-apache-0.0.1-1.x86_64.rpm -O ./dist/nri-apache-0.0.1-1.x86_64.rpm
        wget https://github.com/newrelic/nri-apache/releases/download/v0.0.1/nri-apache_0.0.1-1_amd64.deb -O ./dist/nri-apache_0.0.1-1_amd64.deb
    - uses: ./linux
      with:
        tag: '0.0.1'
        integration: 'nri-apache'
        upgrade: false
  windows:
    runs-on: ubuntu-latest
    name: A job to test created packages
    steps:
      - uses: actions/checkout@v2
      - uses: ./windows
        with:
          message: 'Totally windows'
